<?php

/**
 * PurchaseOrderApi
 * PHP version 7.2
 *
 * @category Class
 * @package  EConnect\Psb
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PSB API 1.0
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: techsupport@econnect.eu
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace EConnect\Psb\Api;

use GuzzleHttp\Psr7\MultipartStream;
use Http\Client\Common\Plugin\ErrorPlugin;
use Http\Client\Common\Plugin\RedirectPlugin;
use Http\Client\Common\PluginClient;
use Http\Client\Common\PluginClientFactory;
use Http\Client\Exception\HttpException;
use Http\Client\HttpAsyncClient;
use Http\Discovery\HttpAsyncClientDiscovery;
use Http\Discovery\Psr17FactoryDiscovery;
use Http\Discovery\Psr18ClientDiscovery;
use Http\Promise\Promise;
use EConnect\Psb\ApiException;
use EConnect\Psb\Configuration;
use EConnect\Psb\DebugPlugin;
use EConnect\Psb\HeaderSelector;
use EConnect\Psb\ObjectSerializer;
use Psr\Http\Client\ClientExceptionInterface;
use Psr\Http\Client\ClientInterface;
use Psr\Http\Message\RequestFactoryInterface;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\StreamFactoryInterface;
use Psr\Http\Message\UriFactoryInterface;
use Psr\Http\Message\UriInterface;

use function sprintf;

/**
 * PurchaseOrderApi Class Doc Comment
 *
 * @category Class
 * @package  EConnect\Psb
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PurchaseOrderApi
{
    /**
     * @var PluginClient
     */
    protected $httpClient;

    /**
     * @var PluginClient
     */
    protected $httpAsyncClient;

    /**
     * @var UriFactoryInterface
     */
    protected $uriFactory;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /**
     * @var RequestFactoryInterface
     */
    protected $requestFactory;

    /**
     * @var StreamFactoryInterface
     */
    protected $streamFactory;

    public function __construct(
        ?ClientInterface $httpClient = null,
        ?Configuration $config = null,
        ?HttpAsyncClient $httpAsyncClient = null,
        ?UriFactoryInterface $uriFactory = null,
        ?RequestFactoryInterface $requestFactory = null,
        ?StreamFactoryInterface $streamFactory = null,
        ?HeaderSelector $selector = null,
        ?array $plugins = null,
        $hostIndex = 0
    ) {
        $this->config = $config ?? Configuration::getDefaultConfiguration();
        $this->requestFactory = $requestFactory ?? Psr17FactoryDiscovery::findRequestFactory();
        $this->streamFactory = $streamFactory ?? Psr17FactoryDiscovery::findStreamFactory();

        $plugins = $plugins ?? [
            new RedirectPlugin(['strict' => true]),
            new ErrorPlugin(),
        ];

        if ($this->config->getDebug()) {
            $plugins[] = new DebugPlugin(fopen($this->config->getDebugFile(), 'ab'));
        }

        $this->httpClient = (new PluginClientFactory())->createClient(
            $httpClient ?? Psr18ClientDiscovery::find(),
            $plugins
        );

        $this->httpAsyncClient = (new PluginClientFactory())->createClient(
            $httpAsyncClient ?? HttpAsyncClientDiscovery::find(),
            $plugins
        );

        $this->uriFactory = $uriFactory ?? Psr17FactoryDiscovery::findUriFactory();

        $this->headerSelector = $selector ?? new HeaderSelector();

        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation apiV1PartyIdPurchaseOrderDocumentIdStatusGet
     *
     * Get purchase order statuses (FOR DEBUGGING ONLY).
     *
     * @param  string $party_id The sender (buyer) partyId. (required)
     * @param  string $document_id The service bus documentId. (required)
     *
     * @throws \EConnect\Psb\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \EConnect\Psb\Model\DocumentStatus[]
     */
    public function apiV1PartyIdPurchaseOrderDocumentIdStatusGet($party_id, $document_id)
    {
        list($response) = $this->apiV1PartyIdPurchaseOrderDocumentIdStatusGetWithHttpInfo($party_id, $document_id);
        return $response;
    }

    /**
     * Operation apiV1PartyIdPurchaseOrderDocumentIdStatusGetWithHttpInfo
     *
     * Get purchase order statuses (FOR DEBUGGING ONLY).
     *
     * @param  string $party_id The sender (buyer) partyId. (required)
     * @param  string $document_id The service bus documentId. (required)
     *
     * @throws \EConnect\Psb\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array{0: \EConnect\Psb\Model\DocumentStatus[], 1: int, 2: string[]} array of \EConnect\Psb\Model\DocumentStatus[], HTTP status code, HTTP response headers (array of strings)
     */
    public function apiV1PartyIdPurchaseOrderDocumentIdStatusGetWithHttpInfo($party_id, $document_id)
    {
        $request = $this->apiV1PartyIdPurchaseOrderDocumentIdStatusGetRequest($party_id, $document_id);

        try {
            try {
                $response = $this->httpClient->sendRequest($request);
            } catch (HttpException $e) {
                $response = $e->getResponse();
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $response->getStatusCode(),
                        (string) $request->getUri()
                    ),
                    $request,
                    $response,
                    $e
                );
            } catch (ClientExceptionInterface $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $request,
                    null,
                    $e
                );
            }

            $statusCode = $response->getStatusCode();

            switch ($statusCode) {
                case 200:
                    if ('\EConnect\Psb\Model\DocumentStatus[]' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\EConnect\Psb\Model\DocumentStatus[]', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\EConnect\Psb\Model\DocumentStatus[]';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EConnect\Psb\Model\DocumentStatus[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation apiV1PartyIdPurchaseOrderDocumentIdStatusGetAsync
     *
     * Get purchase order statuses (FOR DEBUGGING ONLY).
     *
     * @param  string $party_id The sender (buyer) partyId. (required)
     * @param  string $document_id The service bus documentId. (required)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function apiV1PartyIdPurchaseOrderDocumentIdStatusGetAsync($party_id, $document_id)
    {
        return $this->apiV1PartyIdPurchaseOrderDocumentIdStatusGetAsyncWithHttpInfo($party_id, $document_id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation apiV1PartyIdPurchaseOrderDocumentIdStatusGetAsyncWithHttpInfo
     *
     * Get purchase order statuses (FOR DEBUGGING ONLY).
     *
     * @param  string $party_id The sender (buyer) partyId. (required)
     * @param  string $document_id The service bus documentId. (required)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function apiV1PartyIdPurchaseOrderDocumentIdStatusGetAsyncWithHttpInfo($party_id, $document_id)
    {
        $returnType = '\EConnect\Psb\Model\DocumentStatus[]';
        $request = $this->apiV1PartyIdPurchaseOrderDocumentIdStatusGetRequest($party_id, $document_id);

        return $this->httpAsyncClient->sendAsyncRequest($request)
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function (HttpException $exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $exception->getRequest(),
                        $exception->getResponse(),
                        $exception
                    );
                }
            );
    }

    /**
     * Create request for operation 'apiV1PartyIdPurchaseOrderDocumentIdStatusGet'
     *
     * @param  string $party_id The sender (buyer) partyId. (required)
     * @param  string $document_id The service bus documentId. (required)
     *
     * @throws \InvalidArgumentException
     * @return RequestInterface
     */
    public function apiV1PartyIdPurchaseOrderDocumentIdStatusGetRequest($party_id, $document_id)
    {
        // verify the required parameter 'party_id' is set
        if ($party_id === null || (is_array($party_id) && count($party_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $party_id when calling apiV1PartyIdPurchaseOrderDocumentIdStatusGet'
            );
        }
        if (!preg_match("/[A-Za-z0-9-=:]+/", $party_id)) {
            throw new \InvalidArgumentException("invalid value for \"party_id\" when calling PurchaseOrderApi.apiV1PartyIdPurchaseOrderDocumentIdStatusGet, must conform to the pattern /[A-Za-z0-9-=:]+/.");
        }

        // verify the required parameter 'document_id' is set
        if ($document_id === null || (is_array($document_id) && count($document_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $document_id when calling apiV1PartyIdPurchaseOrderDocumentIdStatusGet'
            );
        }
        if (strlen($document_id) > 256) {
            throw new \InvalidArgumentException('invalid length for "$document_id" when calling PurchaseOrderApi.apiV1PartyIdPurchaseOrderDocumentIdStatusGet, must be smaller than or equal to 256.');
        }


        $resourcePath = '/api/v1/{partyId}/purchaseOrder/{documentId}/status';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = null;
        $multipart = false;



        // path params
        if ($party_id !== null) {
            $resourcePath = str_replace(
                '{' . 'partyId' . '}',
                ObjectSerializer::toPathValue($party_id),
                $resourcePath
            );
        }
        // path params
        if ($document_id !== null) {
            $resourcePath = str_replace(
                '{' . 'documentId' . '}',
                ObjectSerializer::toPathValue($document_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            '',
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

                // Manually set the `Content-Type` header
                $headers['Content-Type'] = "multipart/form-data; boundary={$httpBody->getBoundary()}";

            } elseif ($this->headerSelector->isJsonMime($headers['Content-Type'])) {
                $httpBody = json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Subscription-Key');
        if ($apiKey !== null) {
            $headers['Subscription-Key'] = $apiKey;
        }
        // this endpoint requires OAuth (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = $this->config->getDefaultHeaders();
		if ($this->config->getUserAgent()) {
			$defaultHeaders['User-Agent'] = $this->config->getUserAgent();
		}

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();

        $uri = $this->createUri($operationHost, $resourcePath, $queryParams);

        return $this->createRequest('GET', $uri, $headers, $httpBody);
    }

    /**
     * Operation apiV1PartyIdPurchaseOrderQueryRecipientPartyPost
     *
     * Lookup the recipient party (seller) for possible delivery.
     *
     * @param  string $party_id The sender (buyer) partyId. (required)
     * @param  string[] $request_body All possible partyIds of the recipient party. (required)
     * @param  string $preferred_document_type_id The source or preferred documentTypeId to match with and to determine the partyId format. (optional)
     * @param  \EConnect\Psb\Model\OrderDocumentFamily $document_family Document family (optional)
     *
     * @throws \EConnect\Psb\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \EConnect\Psb\Model\LookupParty
     */
    public function apiV1PartyIdPurchaseOrderQueryRecipientPartyPost($party_id, $request_body, $preferred_document_type_id = null, $document_family = null)
    {
        list($response) = $this->apiV1PartyIdPurchaseOrderQueryRecipientPartyPostWithHttpInfo($party_id, $request_body, $preferred_document_type_id, $document_family);
        return $response;
    }

    /**
     * Operation apiV1PartyIdPurchaseOrderQueryRecipientPartyPostWithHttpInfo
     *
     * Lookup the recipient party (seller) for possible delivery.
     *
     * @param  string $party_id The sender (buyer) partyId. (required)
     * @param  string[] $request_body All possible partyIds of the recipient party. (required)
     * @param  string $preferred_document_type_id The source or preferred documentTypeId to match with and to determine the partyId format. (optional)
     * @param  \EConnect\Psb\Model\OrderDocumentFamily $document_family Document family (optional)
     *
     * @throws \EConnect\Psb\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array{0: \EConnect\Psb\Model\LookupParty, 1: int, 2: string[]} array of \EConnect\Psb\Model\LookupParty, HTTP status code, HTTP response headers (array of strings)
     */
    public function apiV1PartyIdPurchaseOrderQueryRecipientPartyPostWithHttpInfo($party_id, $request_body, $preferred_document_type_id = null, $document_family = null)
    {
        $request = $this->apiV1PartyIdPurchaseOrderQueryRecipientPartyPostRequest($party_id, $request_body, $preferred_document_type_id, $document_family);

        try {
            try {
                $response = $this->httpClient->sendRequest($request);
            } catch (HttpException $e) {
                $response = $e->getResponse();
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $response->getStatusCode(),
                        (string) $request->getUri()
                    ),
                    $request,
                    $response,
                    $e
                );
            } catch (ClientExceptionInterface $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $request,
                    null,
                    $e
                );
            }

            $statusCode = $response->getStatusCode();

            switch ($statusCode) {
                case 200:
                    if ('\EConnect\Psb\Model\LookupParty' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\EConnect\Psb\Model\LookupParty', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\EConnect\Psb\Model\LookupParty';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EConnect\Psb\Model\LookupParty',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation apiV1PartyIdPurchaseOrderQueryRecipientPartyPostAsync
     *
     * Lookup the recipient party (seller) for possible delivery.
     *
     * @param  string $party_id The sender (buyer) partyId. (required)
     * @param  string[] $request_body All possible partyIds of the recipient party. (required)
     * @param  string $preferred_document_type_id The source or preferred documentTypeId to match with and to determine the partyId format. (optional)
     * @param  \EConnect\Psb\Model\OrderDocumentFamily $document_family Document family (optional)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function apiV1PartyIdPurchaseOrderQueryRecipientPartyPostAsync($party_id, $request_body, $preferred_document_type_id = null, $document_family = null)
    {
        return $this->apiV1PartyIdPurchaseOrderQueryRecipientPartyPostAsyncWithHttpInfo($party_id, $request_body, $preferred_document_type_id, $document_family)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation apiV1PartyIdPurchaseOrderQueryRecipientPartyPostAsyncWithHttpInfo
     *
     * Lookup the recipient party (seller) for possible delivery.
     *
     * @param  string $party_id The sender (buyer) partyId. (required)
     * @param  string[] $request_body All possible partyIds of the recipient party. (required)
     * @param  string $preferred_document_type_id The source or preferred documentTypeId to match with and to determine the partyId format. (optional)
     * @param  \EConnect\Psb\Model\OrderDocumentFamily $document_family Document family (optional)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function apiV1PartyIdPurchaseOrderQueryRecipientPartyPostAsyncWithHttpInfo($party_id, $request_body, $preferred_document_type_id = null, $document_family = null)
    {
        $returnType = '\EConnect\Psb\Model\LookupParty';
        $request = $this->apiV1PartyIdPurchaseOrderQueryRecipientPartyPostRequest($party_id, $request_body, $preferred_document_type_id, $document_family);

        return $this->httpAsyncClient->sendAsyncRequest($request)
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function (HttpException $exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $exception->getRequest(),
                        $exception->getResponse(),
                        $exception
                    );
                }
            );
    }

    /**
     * Create request for operation 'apiV1PartyIdPurchaseOrderQueryRecipientPartyPost'
     *
     * @param  string $party_id The sender (buyer) partyId. (required)
     * @param  string[] $request_body All possible partyIds of the recipient party. (required)
     * @param  string $preferred_document_type_id The source or preferred documentTypeId to match with and to determine the partyId format. (optional)
     * @param  \EConnect\Psb\Model\OrderDocumentFamily $document_family Document family (optional)
     *
     * @throws \InvalidArgumentException
     * @return RequestInterface
     */
    public function apiV1PartyIdPurchaseOrderQueryRecipientPartyPostRequest($party_id, $request_body, $preferred_document_type_id = null, $document_family = null)
    {
        // verify the required parameter 'party_id' is set
        if ($party_id === null || (is_array($party_id) && count($party_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $party_id when calling apiV1PartyIdPurchaseOrderQueryRecipientPartyPost'
            );
        }
        if (!preg_match("/[A-Za-z0-9-=:]+/", $party_id)) {
            throw new \InvalidArgumentException("invalid value for \"party_id\" when calling PurchaseOrderApi.apiV1PartyIdPurchaseOrderQueryRecipientPartyPost, must conform to the pattern /[A-Za-z0-9-=:]+/.");
        }

        // verify the required parameter 'request_body' is set
        if ($request_body === null || (is_array($request_body) && count($request_body) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $request_body when calling apiV1PartyIdPurchaseOrderQueryRecipientPartyPost'
            );
        }
        if ($preferred_document_type_id !== null && !preg_match("/[A-Za-z0-9-:.]{1,}[#]{2}[A-Za-z0-9-:.#*]{1,}|^$/", $preferred_document_type_id)) {
            throw new \InvalidArgumentException("invalid value for \"preferred_document_type_id\" when calling PurchaseOrderApi.apiV1PartyIdPurchaseOrderQueryRecipientPartyPost, must conform to the pattern /[A-Za-z0-9-:.]{1,}[#]{2}[A-Za-z0-9-:.#*]{1,}|^$/.");
        }


        $resourcePath = '/api/v1/{partyId}/purchaseOrder/queryRecipientParty';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = null;
        $multipart = false;

        // query params
        if ($preferred_document_type_id !== null) {
            if ('form' === 'form' && is_array($preferred_document_type_id)) {
                foreach ($preferred_document_type_id as $key => $value) {
                    $queryParams[$key] = $value;
                }
            } else {
                $queryParams['preferredDocumentTypeId'] = $preferred_document_type_id;
            }
        }
        // query params
        if ($document_family !== null) {
            if ('form' === 'form' && is_array($document_family)) {
                foreach ($document_family as $key => $value) {
                    $queryParams[$key] = $value;
                }
            } else {
                $queryParams['documentFamily'] = $document_family;
            }
        }


        // path params
        if ($party_id !== null) {
            $resourcePath = str_replace(
                '{' . 'partyId' . '}',
                ObjectSerializer::toPathValue($party_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            'application/json',
            $multipart
        );

        // for model (json/xml)
        if (isset($request_body)) {
            if ($this->headerSelector->isJsonMime($headers['Content-Type'])) {
                $httpBody = json_encode(ObjectSerializer::sanitizeForSerialization($request_body));
            } else {
                $httpBody = $request_body;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

                // Manually set the `Content-Type` header
                $headers['Content-Type'] = "multipart/form-data; boundary={$httpBody->getBoundary()}";

            } elseif ($this->headerSelector->isJsonMime($headers['Content-Type'])) {
                $httpBody = json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Subscription-Key');
        if ($apiKey !== null) {
            $headers['Subscription-Key'] = $apiKey;
        }
        // this endpoint requires OAuth (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = $this->config->getDefaultHeaders();
		if ($this->config->getUserAgent()) {
			$defaultHeaders['User-Agent'] = $this->config->getUserAgent();
		}

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();

        $uri = $this->createUri($operationHost, $resourcePath, $queryParams);

        return $this->createRequest('POST', $uri, $headers, $httpBody);
    }

    /**
     * Operation sendOrderCancellation
     *
     * Send order cancellation to let the seller know the order is cancelled.
     *
     * @param  string $party_id Your partyId (buyer). (required)
     * @param  string $document_id DocumentId that the cancellation is about. (required)
     * @param  \EConnect\Psb\Model\OrderCancellation $order_cancellation Order cancellation message. (required)
     *
     * @throws \EConnect\Psb\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \EConnect\Psb\Model\Document
     */
    public function sendOrderCancellation($party_id, $document_id, $order_cancellation)
    {
        list($response) = $this->sendOrderCancellationWithHttpInfo($party_id, $document_id, $order_cancellation);
        return $response;
    }

    /**
     * Operation sendOrderCancellationWithHttpInfo
     *
     * Send order cancellation to let the seller know the order is cancelled.
     *
     * @param  string $party_id Your partyId (buyer). (required)
     * @param  string $document_id DocumentId that the cancellation is about. (required)
     * @param  \EConnect\Psb\Model\OrderCancellation $order_cancellation Order cancellation message. (required)
     *
     * @throws \EConnect\Psb\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array{0: \EConnect\Psb\Model\Document, 1: int, 2: string[]} array of \EConnect\Psb\Model\Document, HTTP status code, HTTP response headers (array of strings)
     */
    public function sendOrderCancellationWithHttpInfo($party_id, $document_id, $order_cancellation)
    {
        $request = $this->sendOrderCancellationRequest($party_id, $document_id, $order_cancellation);

        try {
            try {
                $response = $this->httpClient->sendRequest($request);
            } catch (HttpException $e) {
                $response = $e->getResponse();
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $response->getStatusCode(),
                        (string) $request->getUri()
                    ),
                    $request,
                    $response,
                    $e
                );
            } catch (ClientExceptionInterface $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $request,
                    null,
                    $e
                );
            }

            $statusCode = $response->getStatusCode();

            switch ($statusCode) {
                case 200:
                    if ('\EConnect\Psb\Model\Document' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\EConnect\Psb\Model\Document', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\EConnect\Psb\Model\Document';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EConnect\Psb\Model\Document',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation sendOrderCancellationAsync
     *
     * Send order cancellation to let the seller know the order is cancelled.
     *
     * @param  string $party_id Your partyId (buyer). (required)
     * @param  string $document_id DocumentId that the cancellation is about. (required)
     * @param  \EConnect\Psb\Model\OrderCancellation $order_cancellation Order cancellation message. (required)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function sendOrderCancellationAsync($party_id, $document_id, $order_cancellation)
    {
        return $this->sendOrderCancellationAsyncWithHttpInfo($party_id, $document_id, $order_cancellation)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation sendOrderCancellationAsyncWithHttpInfo
     *
     * Send order cancellation to let the seller know the order is cancelled.
     *
     * @param  string $party_id Your partyId (buyer). (required)
     * @param  string $document_id DocumentId that the cancellation is about. (required)
     * @param  \EConnect\Psb\Model\OrderCancellation $order_cancellation Order cancellation message. (required)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function sendOrderCancellationAsyncWithHttpInfo($party_id, $document_id, $order_cancellation)
    {
        $returnType = '\EConnect\Psb\Model\Document';
        $request = $this->sendOrderCancellationRequest($party_id, $document_id, $order_cancellation);

        return $this->httpAsyncClient->sendAsyncRequest($request)
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function (HttpException $exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $exception->getRequest(),
                        $exception->getResponse(),
                        $exception
                    );
                }
            );
    }

    /**
     * Create request for operation 'sendOrderCancellation'
     *
     * @param  string $party_id Your partyId (buyer). (required)
     * @param  string $document_id DocumentId that the cancellation is about. (required)
     * @param  \EConnect\Psb\Model\OrderCancellation $order_cancellation Order cancellation message. (required)
     *
     * @throws \InvalidArgumentException
     * @return RequestInterface
     */
    public function sendOrderCancellationRequest($party_id, $document_id, $order_cancellation)
    {
        // verify the required parameter 'party_id' is set
        if ($party_id === null || (is_array($party_id) && count($party_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $party_id when calling sendOrderCancellation'
            );
        }
        if (!preg_match("/[A-Za-z0-9-=:]+/", $party_id)) {
            throw new \InvalidArgumentException("invalid value for \"party_id\" when calling PurchaseOrderApi.sendOrderCancellation, must conform to the pattern /[A-Za-z0-9-=:]+/.");
        }

        // verify the required parameter 'document_id' is set
        if ($document_id === null || (is_array($document_id) && count($document_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $document_id when calling sendOrderCancellation'
            );
        }
        if (strlen($document_id) > 256) {
            throw new \InvalidArgumentException('invalid length for "$document_id" when calling PurchaseOrderApi.sendOrderCancellation, must be smaller than or equal to 256.');
        }

        // verify the required parameter 'order_cancellation' is set
        if ($order_cancellation === null || (is_array($order_cancellation) && count($order_cancellation) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $order_cancellation when calling sendOrderCancellation'
            );
        }

        $resourcePath = '/api/v1/{partyId}/purchaseOrder/{documentId}/cancel';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = null;
        $multipart = false;



        // path params
        if ($party_id !== null) {
            $resourcePath = str_replace(
                '{' . 'partyId' . '}',
                ObjectSerializer::toPathValue($party_id),
                $resourcePath
            );
        }
        // path params
        if ($document_id !== null) {
            $resourcePath = str_replace(
                '{' . 'documentId' . '}',
                ObjectSerializer::toPathValue($document_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            'application/json',
            $multipart
        );

        // for model (json/xml)
        if (isset($order_cancellation)) {
            if ($this->headerSelector->isJsonMime($headers['Content-Type'])) {
                $httpBody = json_encode(ObjectSerializer::sanitizeForSerialization($order_cancellation));
            } else {
                $httpBody = $order_cancellation;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

                // Manually set the `Content-Type` header
                $headers['Content-Type'] = "multipart/form-data; boundary={$httpBody->getBoundary()}";

            } elseif ($this->headerSelector->isJsonMime($headers['Content-Type'])) {
                $httpBody = json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Subscription-Key');
        if ($apiKey !== null) {
            $headers['Subscription-Key'] = $apiKey;
        }
        // this endpoint requires OAuth (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = $this->config->getDefaultHeaders();
		if ($this->config->getUserAgent()) {
			$defaultHeaders['User-Agent'] = $this->config->getUserAgent();
		}

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();

        $uri = $this->createUri($operationHost, $resourcePath, $queryParams);

        return $this->createRequest('POST', $uri, $headers, $httpBody);
    }

    /**
     * Operation sendPurchaseOrder
     *
     * Send a purchase order.
     *
     * @param  string $party_id The sender (buyer) partyId. (required)
     * @param  \SplFileObject $file Multipart file upload. (required)
     * @param  string $receiver_id An optional receiver partyId to enforce delivery to a specific endpoint. The receiverId will be injected into the document. (optional)
     * @param  string $channel An optional parameter to enforce the use of a delivery channel. (optional)
     *
     * @throws \EConnect\Psb\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \EConnect\Psb\Model\Document
     */
    public function sendPurchaseOrder($party_id, $file, $receiver_id = null, $channel = null)
    {
        list($response) = $this->sendPurchaseOrderWithHttpInfo($party_id, $file, $receiver_id, $channel);
        return $response;
    }

    /**
     * Operation sendPurchaseOrderWithHttpInfo
     *
     * Send a purchase order.
     *
     * @param  string $party_id The sender (buyer) partyId. (required)
     * @param  \SplFileObject $file Multipart file upload. (required)
     * @param  string $receiver_id An optional receiver partyId to enforce delivery to a specific endpoint. The receiverId will be injected into the document. (optional)
     * @param  string $channel An optional parameter to enforce the use of a delivery channel. (optional)
     *
     * @throws \EConnect\Psb\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array{0: \EConnect\Psb\Model\Document, 1: int, 2: string[]} array of \EConnect\Psb\Model\Document, HTTP status code, HTTP response headers (array of strings)
     */
    public function sendPurchaseOrderWithHttpInfo($party_id, $file, $receiver_id = null, $channel = null)
    {
        $request = $this->sendPurchaseOrderRequest($party_id, $file, $receiver_id, $channel);

        try {
            try {
                $response = $this->httpClient->sendRequest($request);
            } catch (HttpException $e) {
                $response = $e->getResponse();
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $response->getStatusCode(),
                        (string) $request->getUri()
                    ),
                    $request,
                    $response,
                    $e
                );
            } catch (ClientExceptionInterface $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $request,
                    null,
                    $e
                );
            }

            $statusCode = $response->getStatusCode();

            switch ($statusCode) {
                case 200:
                    if ('\EConnect\Psb\Model\Document' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\EConnect\Psb\Model\Document', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\EConnect\Psb\Model\Document';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EConnect\Psb\Model\Document',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation sendPurchaseOrderAsync
     *
     * Send a purchase order.
     *
     * @param  string $party_id The sender (buyer) partyId. (required)
     * @param  \SplFileObject $file Multipart file upload. (required)
     * @param  string $receiver_id An optional receiver partyId to enforce delivery to a specific endpoint. The receiverId will be injected into the document. (optional)
     * @param  string $channel An optional parameter to enforce the use of a delivery channel. (optional)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function sendPurchaseOrderAsync($party_id, $file, $receiver_id = null, $channel = null)
    {
        return $this->sendPurchaseOrderAsyncWithHttpInfo($party_id, $file, $receiver_id, $channel)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation sendPurchaseOrderAsyncWithHttpInfo
     *
     * Send a purchase order.
     *
     * @param  string $party_id The sender (buyer) partyId. (required)
     * @param  \SplFileObject $file Multipart file upload. (required)
     * @param  string $receiver_id An optional receiver partyId to enforce delivery to a specific endpoint. The receiverId will be injected into the document. (optional)
     * @param  string $channel An optional parameter to enforce the use of a delivery channel. (optional)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function sendPurchaseOrderAsyncWithHttpInfo($party_id, $file, $receiver_id = null, $channel = null)
    {
        $returnType = '\EConnect\Psb\Model\Document';
        $request = $this->sendPurchaseOrderRequest($party_id, $file, $receiver_id, $channel);

        return $this->httpAsyncClient->sendAsyncRequest($request)
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function (HttpException $exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $exception->getRequest(),
                        $exception->getResponse(),
                        $exception
                    );
                }
            );
    }

    /**
     * Create request for operation 'sendPurchaseOrder'
     *
     * @param  string $party_id The sender (buyer) partyId. (required)
     * @param  \SplFileObject $file Multipart file upload. (required)
     * @param  string $receiver_id An optional receiver partyId to enforce delivery to a specific endpoint. The receiverId will be injected into the document. (optional)
     * @param  string $channel An optional parameter to enforce the use of a delivery channel. (optional)
     *
     * @throws \InvalidArgumentException
     * @return RequestInterface
     */
    public function sendPurchaseOrderRequest($party_id, $file, $receiver_id = null, $channel = null)
    {
        // verify the required parameter 'party_id' is set
        if ($party_id === null || (is_array($party_id) && count($party_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $party_id when calling sendPurchaseOrder'
            );
        }
        if (!preg_match("/[A-Za-z0-9-=:]+/", $party_id)) {
            throw new \InvalidArgumentException("invalid value for \"party_id\" when calling PurchaseOrderApi.sendPurchaseOrder, must conform to the pattern /[A-Za-z0-9-=:]+/.");
        }

        // verify the required parameter 'file' is set
        if ($file === null || (is_array($file) && count($file) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $file when calling sendPurchaseOrder'
            );
        }
        if ($receiver_id !== null && !preg_match("/[A-Za-z0-9-=:]+/", $receiver_id)) {
            throw new \InvalidArgumentException("invalid value for \"receiver_id\" when calling PurchaseOrderApi.sendPurchaseOrder, must conform to the pattern /[A-Za-z0-9-=:]+/.");
        }


        $resourcePath = '/api/v1/{partyId}/purchaseOrder/send';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = null;
        $multipart = false;

        // query params
        if ($receiver_id !== null) {
            if ('form' === 'form' && is_array($receiver_id)) {
                foreach ($receiver_id as $key => $value) {
                    $queryParams[$key] = $value;
                }
            } else {
                $queryParams['receiverId'] = $receiver_id;
            }
        }
        // query params
        if ($channel !== null) {
            if ('form' === 'form' && is_array($channel)) {
                foreach ($channel as $key => $value) {
                    $queryParams[$key] = $value;
                }
            } else {
                $queryParams['channel'] = $channel;
            }
        }


        // path params
        if ($party_id !== null) {
            $resourcePath = str_replace(
                '{' . 'partyId' . '}',
                ObjectSerializer::toPathValue($party_id),
                $resourcePath
            );
        }

        // form params
        if ($file !== null) {
            $multipart = true;
            $formParams['file'] = [];
            $paramFiles = is_array($file) ? $file : [$file];
            foreach ($paramFiles as $paramFile) {
                $formParams['file'][] = \GuzzleHttp\Psr7\try_fopen(
                    ObjectSerializer::toFormValue($paramFile),
                    'rb'
                );
            }
        }

        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            'multipart/form-data',
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

                // Manually set the `Content-Type` header
                $headers['Content-Type'] = "multipart/form-data; boundary={$httpBody->getBoundary()}";

            } elseif ($this->headerSelector->isJsonMime($headers['Content-Type'])) {
                $httpBody = json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Subscription-Key');
        if ($apiKey !== null) {
            $headers['Subscription-Key'] = $apiKey;
        }
        // this endpoint requires OAuth (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = $this->config->getDefaultHeaders();
		if ($this->config->getUserAgent()) {
			$defaultHeaders['User-Agent'] = $this->config->getUserAgent();
		}

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();

        $uri = $this->createUri($operationHost, $resourcePath, $queryParams);

        return $this->createRequest('POST', $uri, $headers, $httpBody);
    }


    /**
     * @param string $method
     * @param string|UriInterface $uri
     * @param array $headers
     * @param string|StreamInterface|null $body
     *
     * @return RequestInterface
     */
    protected function createRequest(string $method, $uri, array $headers = [], $body = null): RequestInterface
    {
        if (is_string($body) && '' !== $body && null === $this->streamFactory) {
            throw new \RuntimeException('Cannot create request: A stream factory is required to create a request with a non-empty string body.');
        }

        $request = $this->requestFactory->createRequest($method, $uri);

        foreach ($headers as $key => $value) {
            $request = $request->withHeader($key, $value);
        }

        if (null !== $body && '' !== $body) {
            $request = $request->withBody(
                is_string($body) ? $this->streamFactory->createStream($body) : $body
            );
        }

        return $request;
    }

    private function createUri(
        string $operationHost,
        string $resourcePath,
        array $queryParams
    ): UriInterface {
        $parsedUrl = parse_url($operationHost);

        $host = $parsedUrl['host'] ?? null;
        $scheme = $parsedUrl['scheme'] ?? null;
        $basePath = $parsedUrl['path'] ?? null;
        $port = $parsedUrl['port'] ?? null;
        $user = $parsedUrl['user'] ?? null;
        $password = $parsedUrl['pass'] ?? null;

        $uri = $this->uriFactory->createUri($basePath . $resourcePath)
            ->withHost($host)
            ->withScheme($scheme)
            ->withPort($port)
            ->withQuery(ObjectSerializer::buildQuery($queryParams));

        if ($user) {
            $uri = $uri->withUserInfo($user, $password);
        }

        return $uri;
    }
}
